name: triggerByPush
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: print server osiokkk
        uses: actions/checkout@v3
      - name: print date
        run: echo $(date)
      - name: build docker image
        run: docker build -t project-x . 
  push_image:
   needs: build
   runs-on: ubuntu-22.04
   steps:
     - name: Push image to ECR
       run: echo "pushing image to ECR"
  Scan_image:
   needs: push_image
   runs-on: ubuntu-22.04
   steps:
     - name: Push image to ECR
       run: |
        echo "Scan Image "
        echo "Ok we are scaning image"
  Runner_info:
   needs: Scan_image
   runs-on: ubuntu-latest
   steps:
     - name: Runneer os 
       run: echo "{{ runner.os }}"
       
